services:
  webhook:
    build: .
    container_name: webhook-alertas
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
